name: Publish branch to maven repository
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish'     
        required: true
        default: main
  push:
    branches:
      - main
jobs:
  publish-branch:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Package app for release
        run: mvn -B clean package -Prelease
      - name: Deploy on ossrh
        run: mvn -B clean deploy -DskipTests
